### ISSUE TITLE
Pre-commit.io has a max size on hooks environments which prevents running Mypy adequately

### ISSUE THREAD

**Issue by ELC** [mozilla-ai/any-agent#137]
With the migration to pre-commit.io from #122 now the linting cannot run mypy with all the necessary dependencies

This is how the pre-commit should look like for mypy:

```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-pyyaml
          - pytest
          - any-agent[dev, all]
```

Now when using mypy with all the dependencies, the service fails to run:

![Image](https://github.com/user-attachments/assets/47fbe917-3351-441f-9681-e80ac93221fa)

I already tried dividing the check in smaller hooks without success, the progress can be seen in #113
